### ISSUE TITLE
camera-app does not have a maintainter

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/camera-app#1]
No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.

The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):

* Triaging bugs
* Fixing bugs
* Vetting and implementing enhancement requests
* Corresponding with the UBports project regarding the app's progress
* Requesting bounties be posted for the app
* Taking lots of pictures (Or just some screenshots... if you're boring.)

**Comment by dark-eye** [comment]
I`m already maintain the clock-app is it ok if I`ll maintain this App too?

**Comment by Flohack74** [comment]
Sure if you are motivated xD

**Comment by dark-eye** [comment]
Yay!

**Comment by Flohack74** [comment]
Then you are maintainer now ;)
