### ISSUE TITLE
Add (if possible by Android hal part) possibility to change default resolution

### ISSUE THREAD

**Issue by Flohack74** [ubports/camera-app#13]
Same reasoning as here: https://github.com/ubports/gallery-app/issues/10 - Sometimes I dont want a picture that has 5MB and a ridiculous high resolution. Just because it can? =)

**Comment by dark-eye** [comment]
I think this feature exists as fine/normal/basic qulity but maybe we cann add more option and add the actual resolution in the option name instead of fine/normal...

**Comment by Flohack74** [comment]
On my N5 this does not what it should:
![zwischenablage01](https://user-images.githubusercontent.com/16186470/28932323-5f9cf420-7879-11e7-8386-0eac357d04bb.png)
You can see the same dimensions for all 3 quality levels, and a strange jump in byte size: the smallest one is medium quality in fact.

**Comment by dark-eye** [comment]
Lol its probably a bug , i think the image is taken with the adjusted resolusion and then scaled up to the native camera resolution.

Ill have alook tonight...

**Comment by Flohack74** [comment]
OK thats the point, if the camera app could store smaller pictures its a benefit for upload times, storage, mobile data limit etc.

**Comment by dark-eye** [comment]
hmm it`s seem that the Fine/normal/basic quality is the encoding quality so it`s not a bug just a missing feature by what i see it seems like an easy feature to add...

 i`ll work on it on the weekend
