### ISSUE TITLE
Unable to add date stamp to photos

### ISSUE THREAD

**Issue by Flohack74** [ubports/camera-app#2]
_From @UKPhil on June 25, 2017 10:48_

Unable to add a time & date stamp to the photos take in both with the camera app and from within the Telegram app.  This is a feature that is needed on a smart phone.

_Copied from original issue: ubports/ubports-touch#130_

**Comment by dark-eye** [comment]
@UKPhil Are you referring to date meta data on the images/videos  or an actual date  string superimposed on the image taken by the camera?

**Comment by UKPhil** [comment]
@dark-eye, with this I meant the actual stamp on the photo. Not the stamp metadata given in the folder view. The stamp so you can view a picture and see when it was taken without viewing where it is stored.

**Comment by dark-eye** [comment]
@UKPhil  Hmm ok got it, Thank you,

i`ll try and do both :) (I noticed that the metadata lacks the date).

However this might mean that the options overlay might require a redesign as this seems to be an option that shouldn't  be under  'quick access' as the current options are.

**Comment by UKPhil** [comment]
Thanks for looking into this. I think it will be a great improvement. EBen if just a basic time and date stamp and them more functionality added later.

**Comment by UKPhil** [comment]
Hi dark-eye, with this being closed, I thought that it was fixed and that it would be in the latest release of Ports. However, after upgrading, I see that it is not. Has this issue been closed down due to it recorded under https://github.com/ubports/camera-app/issues/10 or have I missed something?

**Comment by dark-eye** [comment]
@UKPhil i thought so too... I'll talk with @flohack and see what can be done.

**Comment by dark-eye** [comment]
@UKPhil The camera app update will be delivered to the openstore and you'll be able to update it from there.

**Comment by UKPhil** [comment]
@dark eye great but when will that be and why will it not come as an update to the phone like other app/system updates?

**Comment by dark-eye** [comment]
@UKPhil I`m not quite sure when but i`ll  try and expedite it as much as i can.

**Comment by dark-eye** [comment]
Hey @UKPhil,

It just came to me that i can provide you with the current build of the camera through here :)
here it is : [com.ubuntu.camera_3.0.0.745_armhf.click](https://my.owndrive.com/index.php/s/UhubS8sHkUOEyh6)

Hope it helps,

**Comment by Flohack74** [comment]
@UKPhil @dark-eye The problem is that our automated infra still cannot build the click apps, including version update etc. So the suggested solution is to manually bump the version number, and then publish it to the opernstore, filling in the changelog etc. Thats a bit more work but when it is in openstore our CI will download it from there and include in the devel/rc/stable images.

**Comment by dark-eye** [comment]
@Flohack74 Oh OK i didn't meant to rush, just  thought i`ll solve UKPhil issue and provide him with his own version.

If you want i can upload the clock-app and camera app to the open store but isn't it better that it will come through UBports offical account?

**Comment by Flohack74** [comment]
Yes it would be better. But we struggle maintaining all the core apps, so if you are the official maintainer, you can do that. But please take care to bump the version accordingly, and write a meaningful changelog ;)

**Comment by dark-eye** [comment]
@Flohack74 the sub minor versions are bumped up automatically by the git revision list count is that enough? orshoudl i bump the minor version too?

**Comment by Flohack74** [comment]
If you are fine with that bumping ok. For my Telegram app I dont use them at all, but increase minors only. On adding new features I increase middle one. So if you add a stopwatch, its a new feature, most likely deserves a bigger bump ^^

**Comment by UKPhil** [comment]
I have just updated the camera app via the openstore and the date can be added, thanks for this. I have added it to my M10 and my OnePlus One. The date shows great on the M10. However  on the OnePlus One has got the last three numbers of the year missing. Would this need to be a new issue or would you address this here?

**Comment by dark-eye** [comment]
Hey @UKPhil 
I`ll Reopen this issue,  Can you post a  picture with the clipped date? 

Thanks,

**Comment by UKPhil** [comment]
Thanks for this. This is the picture that I took just on the OnePlus One.

![852530618_140110](https://user-images.githubusercontent.com/29687772/33428067-9bb7d9de-d61b-11e7-9fa2-4c21d75a2b7b.jpeg)

**Comment by dark-eye** [comment]
Oh i see the issue ok ill fix it now. It will be in the next update

**Comment by UKPhil** [comment]
Thanks. 
It is a great feature.
