### ISSUE TITLE
Title of the application untranslatable

### ISSUE THREAD

**Issue by Anne017** [ubports/camera-app#80]
To be confirmed, but I think the title of the application (Camera) is untranslatable.

**Comment by dobey** [comment]
It is definitely translatable (and has already been translated to many languages), but it seems something has broken in the build of camera-app since ubports took over, and the translations are perhaps not getting handled correctly for the .desktop file any longer.

**Comment by dark-eye** [comment]
@Flohack74  It  seems that it was missing from the camera-app.pot  file if i`ll upload an updated pot file would it be ok with the weblate translation?

**Comment by Flohack74** [comment]
Yes sure, just update it.

**Comment by Anne017** [comment]
I confirm this string is now in Weblate and translatable.
Thank you very much!
